### ISSUE TITLE
Autenticação

### ISSUE THREAD

**Issue by Ellemaamorim** [es20232/eqp6#10]
Implementar registro e login de usuários.

**Comment by rfsousa** [comment]
Após a implementação da autenticação, ocorre um erro ao registrar um novo usuário, mas este problema só acontece ao utilizar o MongoDB; funciona corretamente com qualquer outro banco de dados.

> .../venv/lib/python3.11/site-packages/djongo/cursor.py", line 59, in execute
    raise db_exe from e
django.db.utils.DatabaseError

**Comment by rfsousa** [comment]
O problema é com o Djongo. Seria possível escrever consultas no MongoDB apenas com o PyMongo, em vez de utilizar um ORM, no entanto, isso tomaria muito tempo. Optamos por alterar o banco de dados para o PostgreSQL para continuar utilizando um ORM e também devido a uma vulnerabilidade presente no Djongo.
